export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "0123456789",
    img: "john.jpg",
    address: "123 Main St, Phnom Penh, Cambodia",
    password: "hashedpassword1",
    role: "customer",
    isActive: true,
    createdAt: "2023-01-15T10:00:00Z",
  },
  {
    id: 2,
    name: "Sophea Lim",
    email: "sophea@example.com",
    phone: "0987654321",
    img: "sophea.jpg",
    address: "456 Riverside, Siem Reap, Cambodia",
    password: "hashedpassword2",
    role: "customer",
    isActive: true,
    createdAt: "2023-02-20T14:30:00Z",
  },
  {
    id: 3,
    name: "Admin User",
    email: "admin@sabaymall.com",
    phone: "011223344",
    img: "admin.jpg",
    address: "789 Admin Rd, Phnom Penh, Cambodia",
    password: "hashedadminpass",
    role: "admin",
    isActive: true,
    createdAt: "2022-12-01T08:00:00Z",
  },
];
